# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-21 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('detailPageName', models.CharField(max_length=33)),
                ('portID', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=10)),
                ('topology', django_mysql.models.ListTextField(models.IntegerField(blank=True), size=100)),
                ('activityLevel', models.CharField(max_length=44)),
                ('collectionType', models.CharField(max_length=22)),
                ('duration', models.CharField(max_length=33)),
                ('language', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=11), size=100)),
                ('priceLevel', models.IntegerField()),
                ('currency', models.CharField(max_length=22)),
                ('mealInfo', models.CharField(blank=True, max_length=22)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=22)),
                ('shortDescription', models.CharField(max_length=44)),
                ('longDescription', models.CharField(max_length=88)),
                ('externalContent', models.BooleanField(default=False)),
                ('minimumAge', models.IntegerField()),
                ('wheelChairAccessible', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Excursions',
                'verbose_name_plural': 'Excursions',
                'db_table': 'Excursions',
                'ordering': ['name'],
            },
        ),
    ]
